name: Auto Conventional Commit

on:
  workflow_dispatch:

jobs:
  auto_commit:
    runs-on: ubuntu-latest

    steps:
      # Clona el repositorio usando token con permisos de escritura
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_TOKEN }}
          ref: main

      # Configura usuario Git
      - name: Setup Git
        run: |
          git config user.name "Commit Bot"
          git config user.email "ariel5253@misena.edu.co"

      # Modifica o genera cambios automáticamente aquí (OPCIONAL)
      # Si tu flujo requiere cambios automáticos en archivos, colócalo aquí

      # Verifica si hay cambios tras modificaciones automáticas
      - name: Check for changes
        id: git_changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      # Genera diff solo si existen cambios
      - name: Get diff
        id: diff
        if: steps.git_changes.outputs.has_changes == 'true'
        run: |
          DIFF=$(git diff HEAD -- . ':!*.md' ':!*.txt')
          DIFF="${DIFF//'%'/'%25'}"
          DIFF="${DIFF//$'\n'/'%0A'}"
          DIFF="${DIFF//$'\r'/'%0D'}"
          echo "diff=$DIFF" >> $GITHUB_OUTPUT

      # Genera commit message con OpenAI solo si hay cambios
      - name: Generate commit message with OpenAI
        id: ai_commit
        if: steps.git_changes.outputs.has_changes == 'true'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_KEY }}
        run: |
          RESPONSE=$(curl -s https://api.openai.com/v1/chat/completions \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
              "model": "gpt-4",
              "messages": [
                {
                  "role": "system",
                  "content": "Eres un experto en desarrollo backend. Recibirás un git diff y generarás un mensaje de commit siguiendo estrictamente las reglas de Conventional Commits (feat:, fix:, chore:, docs:, etc.). Solo entrega el mensaje del commit, sin explicaciones."
                },
                {
                  "role": "user",
                  "content": "'"${{ steps.diff.outputs.diff }}"'"
                }
              ]
            }' | jq -r '.choices[0].message.content')

          RESPONSE="${RESPONSE//'%'/'%25'}"
          RESPONSE="${RESPONSE//$'\n'/'%0A'}"
          RESPONSE="${RESPONSE//$'\r'/'%0D'}"
          echo "message=$RESPONSE" >> $GITHUB_OUTPUT

      # Realiza commit y push solo si hay cambios
      - name: Commit and push
        if: steps.git_changes.outputs.has_changes == 'true'
        run: |
          git add .
          git commit -m "${{ steps.ai_commit.outputs.message }}"
          git push origin main
